### ISSUE TITLE
Comments in Mermaid files aren't recognised

### ISSUE THREAD

**Issue by ss-raicangu** [craigmac/vim-mermaid#3]
Description
-----------

Mermaid.js supports comments in the following format.

~~~
%% Thanks for maintaining `mermaid` filetype config (^u^) !
~~~
_Ref 1. Syntax with two percent signs._

~~~mermaid
flowchart TD;
  %% Thanks for maintaining `mermaid` filetype config (^u^) !
  Hello
~~~
_Ref 2. Example of comment._

The `ftplugin` mentions comment syntax is undecided. Can we please consider updating this :pray: ?

Link: https://mermaid.js.org/intro/syntax-reference.html#diagram-breaking

Potential patch
---------------

~~~diff
diff --git a/ftplugin/mermaid.vim b/ftplugin/mermaid.vim
index fe84ab3..bc91da7 100644
--- a/ftplugin/mermaid.vim
+++ b/ftplugin/mermaid.vim
@@ -16,10 +16,10 @@ setlocal shiftwidth=2
 setlocal softtabstop=-1
 setlocal tabstop=4
 
-" TODO: comments, formatlist stuff, based on what?
-setlocal comments=b:#,fb:-
-setlocal commentstring=#\ %s
-setlocal formatoptions+=tcqln formatoptions-=r formatoptions-=o
+" TODO: formatlist stuff, based on what?
+setlocal comments=:%%
+setlocal commentstring=%%\ %s
+setlocal formatoptions+=tcqlnro
 setlocal formatlistpat=^\\s*\\d\\+\\.\\s\\+\\\|^\\s*[-*+]\\s\\+\\\|^\\[^\\ze[^\\]]\\+\\]:\\&^.\\{4\\}
 
 if exists('b:undo_ftplugin')
~~~
_Ref 3. `b` flag not kept because Mermaid.js does not require a blank space after comment headers. Added `ro` to format options to allow continuing comments with `i_<Enter>` and `o`/`O`._

Concerns
--------

- [x] If updated, how should this be communicated back to Vim/Neovim maintainers?
- [x] Unsure how to support directives, which are like `%%{...}%%`. Do we even need to?
- [x] Suggested patch is not backwards compatible with `b:#,fb:-`, as I'm unsure of what these represent. Looking for advice here.

**Comment by craigmac** [comment]
Patch added in main, thanks!
